### ISSUE TITLE
Finish CEVAE tutorial

### ISSUE THREAD

**Issue by eb8680** [BasisResearch/chirho#11]
Tasks:
- [x] Add synthetic data from [Pyro CEVAE example](http://pyro.ai/examples/cevae.html) #68 
- [x] Add inference with SVI #68 
- [x] Add evaluation #68 
- [x] #106 Update text
- [ ] Update code and regenerate results following #97
