### ISSUE TITLE
Finish SLC tutorial

### ISSUE THREAD

**Issue by eb8680** [BasisResearch/chirho#13]
Tasks:
- [x] Finish model (add mechanisms and priors)  #72 
- [x] Add dataset (sample from SCM prior predictive, or take from experiments in [paper](http://proceedings.mlr.press/v119/witty20a.html))  #72 
- [x] Add inference with SVI  #72 
- [x] Add evaluation  #72 
- [x] Polish code and update tet #101 
- [ ] Update code and regenerate results once #97 lands on `master`
