### ISSUE TITLE
Improving compatibility with Pyro broadcasting semantics

### ISSUE THREAD

**Issue by eb8680** [BasisResearch/chirho#165]
This issue tracks work toward making `causal_pyro` work correctly and seamlessly with the broadcasting-based implementations of various modeling and inference computations in Pyro.

Points in `causal_pyro` that need new test cases and bugfixes:
- Indexing operations in `causal_pyro.indexed.ops`:
  - [x] `indices_of` - #168 
  - [x] `scatter` - #168 
  - [x] `gather` - #168 
  - [x] `cond` - #141
- Older unit tests in `causal_pyro.counterfactual` that do not use the `indexed` API

Potential points of failure upstream in Pyro that should be fixed by improvements to `indexed` but should still be covered in `causal_pyro` unit tests (it should be straightforward to adapt test cases from Pyro's `test/infer/test_valid_models.py` and `test/infer/test_enum.py`):
- Models and guides:
  - [ ] Nested plate configurations
  - [ ] `max_plate_nesting > 5` (see #46)
  - [ ] `pyro.poutine.mask`
  - [ ] `pyro.poutine.scale`
- Plates used for automatic vectorization in inference:
  - [x] `pyro.infer.Predictive(..., parallel=True)` - #176 
  - [x] `pyro.infer.Trace*_ELBO(..., vectorize_particles=True)` - #176 
  - [x] `pyro.infer.importance.vectorized_importance_weights`
- Enumeration-based ELBO estimators:
  - [x] `pyro.infer.TraceEnum_ELBO` (model-side enumeration) - #176  
  - [x] `pyro.infer.TraceEnum_ELBO` (guide-side enumeration) - #176 
  - [x] `pyro.infer.TraceTMC_ELBO` - #176 
- Other enumeration-based inference:
  - [x] `pyro.infer.TraceEnum_ELBO.compute_marginals` - #176 
  - [x] `pyro.infer.infer_discrete` - #176 
  - [x] `pyro.infer.HMC` - #176 
- Stretch goals
  - `pyro.contrib.funsor`
  - `torch.vmap`
