### ISSUE TITLE
Query handlers should be decoupled from Pyro aliases

### ISSUE THREAD

**Issue by eb8680** [BasisResearch/chirho#388]
We currently use `chirho.interventional.handlers.do` and `chirho.observational.handlers.condition` in most user-facing code and documentation because they are drop-in replacements for `pyro.do` and `pyro.condition` respectively.

However, using `do` and `condition` in library code leads to some internal inconsistencies in API design and semantics that will be annoying to work around in the future. This issue tracks work on switching to using more idiomatic and consistently specified query handlers internally.

Tasks:
- [x] Rename `ConditionMessenger` to `Observations` #389 
- [x] Rename `InterveneMessenger` to `Interventions` #389 
- [ ] Add a first-class `Splits` handler to `chirho.counterfactual.handlers` that inserts `split` operations directly #390 
- [ ] Replace internal uses of `do` with `Interventions` (or `Splits` where `Splits` is correct and more precise)
- [ ] Replace internal uses of `condition` with `Observations`
